[package]
name = "box"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.14"
ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"
serde = "1.0.137"
percent-encoding = "2.1.0"

[dev-dependencies]
rand = "0.8.5"
